apiVersion: apps/v1
kind: Deployment

metadata:
  name: gestionstock-deployment

spec:
  replicas: 2

  selector:
    matchLabels:
      app: gestionstock

  template:
    metadata:
      labels:
        app: gestionstock

    spec:
      containers:
        - name: mon-container
          image: mouhamet07/devops-project:latest
          ports:
            - containerPort: 80