apiVersion: v1
kind: Service
metadata:
  name: gestionstock-service
spec:
  type: NodePort
  selector:
    app: gestionstock
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080